[project]
name = "django-base-site"
description = "A Django project template for creating new Django projects."
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "Django~=5.0",
    "boto3~=1.34",
    "celery~=5.5",
    "crispy-bootstrap5~=2025.4",
    "django-alive~=2.0",
    "django-allauth~=65.0",
    "django-crispy-forms~=2.2",
    "django-maintenance-mode~=0.19",
    "django-storages~=1.8",
    "environs[django]~=14.1",
    "hiredis~=3.0",  # needed for Django's native cache and sessions
    "psycopg2-binary~=2.9",
    "pytest-cov~=7.0",
    "pytest-django~=4.5",
    "python-json-logger~=4.0",
    "redis~=7.1",  # needed for celery
    "uwsgi~=2.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar",
    "django-stubs",
    "django-test-plus",
    # importlib-metadata is a dependency of djlint there is a PR to upgrade it in this issue (https://github.com/Riverside-Healthcare/djLint/pull/504) from 5.2.0 to 6.0.0
    "djlint",
    "ipdb",
    "mkdocs-include-markdown-plugin",
    "mkdocs-linkcheck",
    "mkdocs-material",
    "mkdocstrings[python]",
    "model-bakery",
    "ty",
    "readable-log-formatter",
    "ruff",
    "ruff-lsp",
]

[tool.ty]
# Ty type checker configuration: https://docs.astral.sh/ty/
# Ty is a fast, modern type checker for Python

[tool.django-stubs]
django_settings_module = "config.settings.test_runner"

[tool.pytest.ini_options]
addopts = "--nomigrations --ds config.settings.test_runner --cov-config=config/coverage.ini"

# Python warnings documentation: https://docs.python.org/3/library/warnings.html
filterwarnings = [
    # Set the default behavior for warnings to error, so it forces you to look into fixing them
    "error",
]

[tool.bandit]
exclude_dirs = ["tests", "node_modules"]

[tool.coverage.run]
branch = true
source = ["."]
omit = [
    ".venv/*",
    "manage.py",
    "*migrations*",
]

[tool.coverage.html]
directory = "htmlcov"

[tool.djlint]
indent = 2
profile="django"
max_line_length=120
blank_line_after_tag="endblock,extends,load"
format_css=true
format_js=true
use_gitignore=true
ignore="H030,H031,H017"
exclude="base-email.html"

[tool.djlint.js]
indent_size=2

[tool.djlint.css]
indent_size=2

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # Pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",  # isort
    "D",  # pydocstyle
    "S",  # bandit
]
ignore = ["D100", "D101", "D102", "D103", "D104", "D106", "D107", "D203", "D212", ]

[tool.ruff.lint.per-file-ignores]
"**/{tests}/*" = ["S101"]

[tool.ruff.lint.isort.sections]
"django" = ["django"]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "django", "third-party", "first-party", "local-folder", ]
